### ISSUE TITLE
Project Fluent dependency is incorrectly marked optional

### ISSUE THREAD

**Issue by Pathoschild** [khanshoaib3/stardew-access#165]
Hi!

The `manifest.json` file in 1.5.0-beta incorrectly marks the dependency on Project Fluent as optional, so players without Project Fluent installed see a 'no longer compatible' error ([see sample log](https://smapi.io/log/7d7dc15fbbbb47eda99cac05d67a3552)):

> Skipped mods [...] Stardew Access 1.5.0-beta.1 because it's no longer compatible. Please check for a new version at https://smapi.io/mods

With these details in the log file:
```
Loading mods...
   Stardew Access (from Mods\Stardew Access\stardew-access.dll)...
      Loading KdTreeLib.dll...
      Loading TolkDotNet.dll...
      Detected game patcher in assembly stardew-access.dll.
      Broken code in stardew-access.dll: reference to missing assembly 'ProjectFluent, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'.
```

Removing the `"IsRequired": false` line will let SMAPI show a more informative error message error:
> Skipped mods [...] Stardew Access 1.5.0-beta.1 because it requires mods which aren't installed (Shockah.ProjectFluent).

**Comment by khanshoaib3** [comment]
The reason for using the "isRequired" was that previously we thought of using the smapi translator alongside project fluent, so that way English players won't have to install project fluent.

But, because there are just so many things to translate that I don't think using the smapi translator is feasible if there's a much better option available.

So yeah, we will be removing that line before the next alpha/beta.
I'll use this issue as a reminder and close this once it's done.

Thank you!
