### ISSUE TITLE
I've found some Secret Notes rewards that not reported by Stardew Access

### ISSUE THREAD

**Issue by fz0308** [khanshoaib3/stardew-access#174]
Hello, I've found some Secret Notes rewards that Stardew Access didn't report on
First, Secret Note #16 reward is a Treasure Chest. Go to the Railroad and go to the tile to the right of The Boulder (not Summit Boulder) to be precise next to  12x 38y, and use the hoe right on that tile.
Second, Secret Note #19 reward is a Solid Gold Lewis statue, , go to the tile behind the Manor House, directly next to tile 57x 80y while facing that tile, and press X.
Third, Secret Note #20 reward is Special Charm, exchange the charm with  a Rabbit's Foot. by talking to the truck driver next to The Joja Mart. I'm not sure where the truck is, but I can interact with the truck driver when I was on tiles 106x 51y and 106x 52y when facing left, so perhaps the truck is on 105x 51y to 105x 52y. This Special Charm increase daily luck permanently.
All of this I found out the hard way because Stardew Access doesn't report it. Can you add trucks, Treasure Chest locations, Solid Gold Lewis statue locations, and more to static-tiles.json?

**Comment by Bartholomue** [comment]
I disagree with adding these locations to the static definitions. Sighted players have to read and analyze the map and find their way to the destination, and I've seen a lot of streamers struggle with it, so making it a flat-out designated target would be trivializing the challenge of those secret notes.
FYI The reason Stardew Access doesn't read some secret notes is because some of those are pictures, rather than text (typically a map).

**Comment by fz0308** [comment]
Can you at least add the truck location? Just to let the players know there's a truck there

**Comment by ParadoxiKat** [comment]
Fixed by d17e1492a05adae52636fdf441f73c5133946ddd during 1.6 migration
