### ISSUE TITLE
pressing w to move to the join/host tabs in coop menu jumps immediately back to join game

### ISSUE THREAD

**Issue by lilmike** [khanshoaib3/stardew-access#187]
Hiya,

So as of today, with nothing about stardew valley changed, when I go to coop menu, and try to move to the tabs join/host, it immediately jumps me back to the join game button. I have no idea what's going on, but it's making me unable to host any games. Anyone else ever seen anything like this? I'm using stardew valley for linux from gog.com.

-Michael.

**Comment by khanshoaib3** [comment]
Sorry for replying late, I don't know how I missed this issue.
Anyways, I just checked and looks like the join tab button is snapped at by default when we press `w`.
In order to avoid confusion, the game speaks which tab is currently active or selected i.e., if the host tab is selected then it will say "host tab selected".

**Comment by lilmike** [comment]
Yeah I managed to fix this by reinstalling stardew valley, no idea what
was going wrong.

-Michael.

**Comment by khanshoaib3** [comment]
Oh, well, I'll close this issue then.
