### ISSUE TITLE
CJBCheatsMenu and ItemSpawner

### ISSUE THREAD

**Issue by FranklinLamar888** [khanshoaib3/stardew-access#62]
I wanted to play with CJBCheatsMenu and ItemSpawner, but they are not accessible. I don't know if it would be possible or not, but could you make these modes work with StardewAccess? The ItenSpawner is somewhat accessible, but the CheatsMenu is not.

**Comment by khanshoaib3** [comment]
These are popular mods and do need to be accessible but they need to use the api provided by Stardew Access to make them accessible, i'll see if there is a workaround or i'll implement the api later on.

**Comment by conundrum9999** [comment]
I'm looking to make some mod menus accessible next; from your comment here it seems your preference is to have that implemented on the other mod's side rather than as mod-specific patches within stardew-access?

I'm currently looking at making the happy birthday mod's birthday selection menu accessible; very simple and straight forward. Have already pulled their code down for review and can imagine ways to implement it from either end. If that goes well I'd be happy to tackle CJBCheats next.
